name: my_dbt_project
version: 1.0
config-version: 2
profile: my_profile
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]
packages-install-path: "dbt_packages"
clean-targets: ["target"]
